name: Build & deploy

on:
  push:
    branches:
      - master
  
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14
        cache: 'yarn'
    
    - name: Install NPM packages
      run: yarn
    
    - name: Build project
      run: yarn build
    
    - name: Upload production-ready build files
      uses: actions/upload-artifact@v4
      with:
        name: production-files
        path: ./build
  
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    environment: deploy
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: production-files
        path: ./build
    
    # - name: Upload to QCloud COS
    #   uses: zkqiang/tencent-cos-action@v0.1.0
    #   with:
    #     args: upload -r -s -y ./build internet-temple
    #     secret_id: ${{ secrets.QCLOUD_COS_SECRET_ID }}
    #     secret_key: ${{ secrets.QCLOUD_COS_SECRET_KEY }}
    #     bucket: ${{ secrets.QCLOUD_COS_BUCKET }}
    #     region: ap-shanghai

    - name: Deploy to Aliyun OSS
      uses: fangbinwei/aliyun-oss-website-action@v1
      with:
          accessKeyId: ${{ secrets.ALIYUN_OSS_ACCESS_KEY_ID }}
          accessKeySecret: ${{ secrets.ALIYUN_OSS_ACCESS_KEY_SECRET }}
          bucket: internet-temple
          endpoint: oss-rg-china-mainland.aliyuncs.com
          folder: build
          skipSetting: true
          incremental: false

    # - name: Deploy to gh-pages
    #   uses: peaceiris/actions-gh-pages@v3
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     publish_dir: ./build
    #     cname: internet-temple.std4453.com
